steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_BASE_URL=${_VITE_API_BASE_URL}'
      - '--tag'
      - '${_IMAGE_NAME}:${COMMIT_SHA}'
      - '--tag'
      - '${_IMAGE_NAME}:latest'
      - '.'
images:
  - '${_IMAGE_NAME}:${COMMIT_SHA}'
  - '${_IMAGE_NAME}:latest'

